/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.User;
import shared.HRMInterface;

/**
 *
 * @author jason
 */
public class ChangePassword extends javax.swing.JFrame {
    private HRMInterface service;
    private User loggedInUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangePassword.class.getName());

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(HRMInterface service, User user) {
        this.service = service;
        this.loggedInUser = user;
        initComponents();
    
        setTitle("Change Password");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        newpasswordfield = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        conpasswordfield = new javax.swing.JPasswordField();
        password1 = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        currentpasswordfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Title.setText("Change Password");

        email.setText("Current Password");

        newpasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordfieldActionPerformed(evt);
            }
        });

        password.setText("New Password:");

        conpasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordfieldActionPerformed(evt);
            }
        });

        password1.setText("Confirm Password:");

        login1.setText("Back");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        login.setText("Change");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        currentpasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentpasswordfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(login))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(password1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password)
                            .addComponent(email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(currentpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(newpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login1)
                    .addComponent(login))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordfieldActionPerformed

    private void conpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasswordfieldActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        String role = loggedInUser.getRole();

        if ("HR".equalsIgnoreCase(role)) {

            HR_Main hrmainpage = new HR_Main(service, loggedInUser);
            hrmainpage.setVisible(true);

        } else if ("Employee".equalsIgnoreCase(role)) {

            Employee_Main empMain = new Employee_Main(service, loggedInUser);
            empMain.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Unknown role: " + role,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_login1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {

            String oldPass = new String(currentpasswordfield.getPassword());
            String newPass = new String(newpasswordfield.getPassword());
            String conPass = new String(conpasswordfield.getPassword());

            if (!newPass.equals(conPass)) {
                JOptionPane.showMessageDialog(this,
                        "New password and confirm password do not match",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String result = service.changePassword(
                    loggedInUser.getUserId(),
                    oldPass,
                    newPass
            );

            if ("Password Changed Successfully".equals(result)) {

                JOptionPane.showMessageDialog(this,
                        result,
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                currentpasswordfield.setText("");
                newpasswordfield.setText("");
                conpasswordfield.setText("");
                
                String role = loggedInUser.getRole();

                if ("HR".equalsIgnoreCase(role)) {

                    HR_Main hrmainpage = new HR_Main(service, loggedInUser);
                    hrmainpage.setVisible(true);

                } else if ("Employee".equalsIgnoreCase(role)) {

                    Employee_Main empMain = new Employee_Main(service, loggedInUser);
                    empMain.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(this,
                            "Unknown role: " + role,
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this,
                        result,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Server error: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void currentpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentpasswordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPasswordField conpasswordfield;
    private javax.swing.JPasswordField currentpasswordfield;
    private javax.swing.JLabel email;
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JPasswordField newpasswordfield;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    // End of variables declaration//GEN-END:variables
}
