/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import javax.swing.JOptionPane;
import model.LeaveApplication;
import model.Request;
import model.User;
import shared.HRMInterface;

/**
 *
 * @author jason
 */
public class ApplyLeave extends javax.swing.JFrame {
    private HRMInterface service;
    private User loggedInUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ApplyLeave.class.getName());

    /**
     * Creates new form ApplyLeave
     */
    public ApplyLeave(HRMInterface service, User user) {
        this.service = service;
        this.loggedInUser = user;
        initComponents();
        
        setTitle("Apply Leave");

        setLocationRelativeTo(null);
        
        try {
            int balance = service.checkLeaveBalance(loggedInUser.getUserId());
            balancefield.setText(String.valueOf(balance));
            balancefield.setEditable(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        balancefield = new javax.swing.JTextField();
        startdatefield = new javax.swing.JTextField();
        email2 = new javax.swing.JLabel();
        leavecombobox = new javax.swing.JComboBox<>();
        email3 = new javax.swing.JLabel();
        enddatefield = new javax.swing.JTextField();
        email4 = new javax.swing.JLabel();
        email5 = new javax.swing.JLabel();
        reasonfield = new javax.swing.JTextField();
        login3 = new javax.swing.JButton();
        login2 = new javax.swing.JButton();
        login1 = new javax.swing.JButton();

        email.setText("Email:");

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Title.setText("Apply Leave");

        email1.setText("Leave Balance (Days) ");

        balancefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancefieldActionPerformed(evt);
            }
        });

        startdatefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdatefieldActionPerformed(evt);
            }
        });

        email2.setText("Leave Type");

        leavecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Type --", "Annual", "Sick", "etc." }));

        email3.setText("Start Date (YYYY-MM--DD)");

        enddatefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enddatefieldActionPerformed(evt);
            }
        });

        email4.setText("End Date (YYYY-MM--DD)");

        email5.setText("Reason");

        reasonfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonfieldActionPerformed(evt);
            }
        });

        login3.setText("Back");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login3ActionPerformed(evt);
            }
        });

        login2.setText("Apply");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });

        login1.setText("Clear");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login3)
                        .addGap(62, 62, 62)
                        .addComponent(login2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(login1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reasonfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(email1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balancefield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(startdatefield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(leavecombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(enddatefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(balancefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email2)
                    .addComponent(leavecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startdatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enddatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login3)
                    .addComponent(login2)
                    .addComponent(login1))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void balancefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancefieldActionPerformed

    private void startdatefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdatefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdatefieldActionPerformed

    private void enddatefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enddatefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enddatefieldActionPerformed

    private void reasonfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonfieldActionPerformed

    private void login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login3ActionPerformed
        // TODO add your handling code here:
        String role = loggedInUser.getRole();

        if ("HR".equalsIgnoreCase(role)) {

            HR_Main hrmainpage = new HR_Main(service, loggedInUser);
            hrmainpage.setVisible(true);

        } else if ("Employee".equalsIgnoreCase(role)) {

            Employee_Main empMain = new Employee_Main(service, loggedInUser);
            empMain.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                "Unknown role: " + role,
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_login3ActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        try {
            String leaveText = leavecombobox.getSelectedItem().toString();
            String startdateText = startdatefield.getText().trim();
            String enddateText = enddatefield.getText().trim();
            String reasonText = reasonfield.getText().trim();

            
            if (leaveText.isEmpty() || startdateText.isEmpty() || enddateText.isEmpty() || reasonText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (leavecombobox.getSelectedItem().toString().equals("-- Select Type --")) {JOptionPane.showMessageDialog(this, "Please select a leave type!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd")
                    .withResolverStyle(ResolverStyle.STRICT);

            LocalDate startDate;
            LocalDate endDate;

            try {
                startDate = LocalDate.parse(startdateText, formatter);
            } catch (DateTimeParseException e) {JOptionPane.showMessageDialog(this, "Start Date must be valid and in format YYYY-MM-DD!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            LocalDate today = LocalDate.now();
            if (startDate.isBefore(today)) {JOptionPane.showMessageDialog(this, "Start date cannot be before today!", "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                endDate = LocalDate.parse(enddateText, formatter);
            } catch (DateTimeParseException e) {JOptionPane.showMessageDialog(this, "End Date must be valid and in format YYYY-MM-DD!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (endDate.isBefore(startDate)) {JOptionPane.showMessageDialog(this, "End date cannot be before start date!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            LeaveApplication la = new LeaveApplication(loggedInUser.getUserId(), leaveText, startDate, endDate, reasonText);

            try(Socket socket = new Socket("localhost", 5000)){
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                ObjectInputStream in = new ObjectInputStream(socket.getInputStream());

                Request req = new Request("APPLY_LEAVE", la);
                out.writeObject(req);
                out.flush();
                
                String result = (String) in.readObject();

                if (result.contains("Leave applied")) {
                    JOptionPane.showMessageDialog(this, result, "Success", JOptionPane.INFORMATION_MESSAGE);

                    String role = loggedInUser.getRole();

                    if ("HR".equalsIgnoreCase(role)) {
                        new HR_Main(service, loggedInUser).setVisible(true);
                    } else if ("Employee".equalsIgnoreCase(role)) {
                        new Employee_Main(service, loggedInUser).setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Unknown role: " + role,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, result, "Error", JOptionPane.ERROR_MESSAGE);
                }
                out.close();
                in.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_login2ActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        leavecombobox.setSelectedIndex(0);
        startdatefield.setText("");
        enddatefield.setText("");
        reasonfield.setText("");
    }//GEN-LAST:event_login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField balancefield;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel email4;
    private javax.swing.JLabel email5;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField enddatefield;
    private javax.swing.JComboBox<String> leavecombobox;
    private javax.swing.JButton login1;
    private javax.swing.JButton login2;
    private javax.swing.JButton login3;
    private javax.swing.JTextField reasonfield;
    private javax.swing.JTextField startdatefield;
    // End of variables declaration//GEN-END:variables
}
