/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.*;
import java.net.*;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
import javax.swing.JOptionPane;
import model.EmployeeUser;
import model.HRUser;
import model.Request;
import model.User;
import shared.HRMInterface;

/**
 *
 * @author jason
 */
public class Register extends javax.swing.JFrame {
    private HRMInterface service;
    private User loggedInUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register(HRMInterface service, User user) {
        this.service = service;
        this.loggedInUser = user;
        initComponents();
        
        setTitle("Register User");

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        identification = new javax.swing.JLabel();
        fnamefield = new javax.swing.JTextField();
        lnamefield = new javax.swing.JTextField();
        identificationfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        rolecombobox = new javax.swing.JComboBox<>();
        role = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        login3 = new javax.swing.JButton();

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Title.setText("Register User");

        fname.setText("First Name");

        identification.setText("IC/Passport");

        fnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamefieldActionPerformed(evt);
            }
        });

        lnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnamefieldActionPerformed(evt);
            }
        });

        identificationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificationfieldActionPerformed(evt);
            }
        });

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        lname.setText("Last Name");

        email.setText("Email");

        password.setText("Password");

        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Role --", "HR", "Employee" }));

        role.setText("Role");

        login1.setText("Clear");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        registerbutton.setText("Register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        login3.setText("Back");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(login3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                    .addComponent(registerbutton)
                                    .addGap(30, 30, 30)
                                    .addComponent(login1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lname)
                                        .addComponent(identification)
                                        .addComponent(email)
                                        .addComponent(password)
                                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(identificationfield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(lnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(emailfield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(passwordfield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(fnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(rolecombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Title)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname)
                    .addComponent(fnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identification, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role)
                    .addComponent(rolecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login3)
                    .addComponent(registerbutton)
                    .addComponent(login1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamefieldActionPerformed

    private void lnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnamefieldActionPerformed

    private void identificationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificationfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificationfieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    }//GEN-LAST:event_loginActionPerformed

    private void login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login3ActionPerformed
        // TODO add your handling code here:
        String role = loggedInUser.getRole();

        if ("HR".equalsIgnoreCase(role)) {

            HR_Main hrmainpage = new HR_Main(service, loggedInUser);
            hrmainpage.setVisible(true);

        } else if ("Employee".equalsIgnoreCase(role)) {

            Employee_Main empMain = new Employee_Main(service, loggedInUser);
            empMain.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Unknown role: " + role,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_login3ActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
        try{
            String fnameText = fnamefield.getText().trim();
            String lnameText = lnamefield.getText().trim();
            String icText = identificationfield.getText().trim();
            String emailText = emailfield.getText().trim();
            String passwordText = passwordfield.getText().trim();
            String roleText = rolecombobox.getSelectedItem().toString();

            if (fnameText.isEmpty() || lnameText.isEmpty() || icText.isEmpty() ||
                emailText.isEmpty() || passwordText.isEmpty()) {

                JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!icText.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "IC/Passport must contain only numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!emailText.contains("@") || !emailText.contains(".")) {
                JOptionPane.showMessageDialog(this, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (passwordText.length() < 4) {
                JOptionPane.showMessageDialog(this, "Password must be at least 4 characters!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (roleText.equals("-- Select Role --")) {
                JOptionPane.showMessageDialog(this, "Please select a role!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            User user;

            if (roleText.equalsIgnoreCase("HR")) {
                user = new HRUser(fnameText, lnameText, icText, emailText, passwordText, roleText);
            } else if (roleText.equalsIgnoreCase("Employee")) {
                user = new EmployeeUser(fnameText, lnameText, icText, emailText, passwordText, roleText);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid role!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            System.setProperty("javax.net.ssl.trustStore", "hr_client_trust.jks");
            System.setProperty("javax.net.ssl.trustStorePassword", "admin123");

            SSLSocketFactory factory =
                    (SSLSocketFactory) SSLSocketFactory.getDefault();

            try (
                SSLSocket socket =
                        (SSLSocket) factory.createSocket("192.168.100.41", 5000);

                ObjectOutputStream out =
                        new ObjectOutputStream(socket.getOutputStream());

                ObjectInputStream in =
                        new ObjectInputStream(socket.getInputStream());
            ) {

                out.flush();

                Request req = new Request("REGISTER", user);
                out.writeObject(req);
                out.flush();

                String result = (String) in.readObject();

                if (result.contains("Successfully")) {
                    JOptionPane.showMessageDialog(this, result, "Success", JOptionPane.INFORMATION_MESSAGE);
                    String role = loggedInUser.getRole();

                    if ("HR".equalsIgnoreCase(role)) {

                        HR_Main hrmainpage = new HR_Main(service, loggedInUser);
                        hrmainpage.setVisible(true);

                    } else if ("Employee".equalsIgnoreCase(role)) {

                        Employee_Main empMain = new Employee_Main(service, loggedInUser);
                        empMain.setVisible(true);

                    } else {

                        JOptionPane.showMessageDialog(this,
                                "Unknown role: " + role,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, result, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred", "Error", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        fnamefield.setText("");
        lnamefield.setText("");
        identificationfield.setText("");
        emailfield.setText("");
        passwordfield.setText("");
        rolecombobox.setSelectedIndex(0);
    }//GEN-LAST:event_login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fnamefield;
    private javax.swing.JLabel identification;
    private javax.swing.JTextField identificationfield;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField lnamefield;
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JButton login3;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JButton registerbutton;
    private javax.swing.JLabel role;
    private javax.swing.JComboBox<String> rolecombobox;
    // End of variables declaration//GEN-END:variables
}
