/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import javax.swing.JOptionPane;
import model.User;
import model.PersonalDetail;
import shared.HRMInterface;

/**
 *
 * @author jason
 */
public class UpdatePersonalDetailsPage extends javax.swing.JFrame {
    private HRMInterface service;
    private User loggedInUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdatePersonalDetailsPage.class.getName());
    
    private void loadPersonalDetails() {
        try {
            int userId = loggedInUser.getUserId();

            PersonalDetail detail = service.getPersonalDetailByUserId(userId);

            if (detail != null) {
                phonefield.setText(detail.getPhoneNumber());
                addressfield.setText(detail.getAddress());
                dobfield.setText(detail.getDateOfBirth());

                connamefield.setText(detail.getContactName());
                relationfield.setText(detail.getRelationship());
                connumfield.setText(detail.getContactNumber());
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Failed to load personal details",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Creates new form UpdateProfile
     */
    public UpdatePersonalDetailsPage(HRMInterface service, User user) {
        this.service = service;
        this.loggedInUser = user;
        initComponents();
    
        setTitle("Personal Detail");
        setLocationRelativeTo(null);
        loadPersonalDetails();   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        identification = new javax.swing.JLabel();
        dobfield = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        connamefield = new javax.swing.JTextField();
        login3 = new javax.swing.JButton();
        login2 = new javax.swing.JButton();
        relationfield = new javax.swing.JTextField();
        email1 = new javax.swing.JLabel();
        connumfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressfield = new javax.swing.JTextArea();
        email2 = new javax.swing.JLabel();
        login4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Title.setText("Personal Details");

        fname.setText("Phone Number");

        phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefieldActionPerformed(evt);
            }
        });

        lname.setText("Address");

        identification.setText("Date of Birth (YYYY-MM-DD)");

        dobfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobfieldActionPerformed(evt);
            }
        });

        email.setText("Contact Name");

        connamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connamefieldActionPerformed(evt);
            }
        });

        login3.setText("Back");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login3ActionPerformed(evt);
            }
        });

        login2.setText("Update");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });

        relationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationfieldActionPerformed(evt);
            }
        });

        email1.setText("Relationship");

        connumfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connumfieldActionPerformed(evt);
            }
        });

        addressfield.setColumns(20);
        addressfield.setRows(5);
        jScrollPane1.setViewportView(addressfield);

        email2.setText("Contact Number");

        login4.setText("Main");
        login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fname)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(login2)
                                .addGap(119, 119, 119)
                                .addComponent(login4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(identification)
                                            .addComponent(email))
                                        .addGap(67, 67, 67))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(email1)
                                            .addComponent(email2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(connamefield, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(relationfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(connumfield, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lname)
                                .addGap(178, 178, 178)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phonefield)
                                    .addComponent(jScrollPane1))))
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname)
                    .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identification, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connumfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login3)
                    .addComponent(login2)
                    .addComponent(login4))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void dobfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobfieldActionPerformed

    private void connamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connamefieldActionPerformed

    private void login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login3ActionPerformed
        // TODO add your handling code here:
        PersonalDetailsPage personalpage = new PersonalDetailsPage(service, loggedInUser);
        personalpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login3ActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:
        try {
            String phoneText = phonefield.getText().trim();
            String addressText = addressfield.getText().trim();
            String dobText = dobfield.getText().trim();
            String connameText = connamefield.getText().trim();
            String relationText = relationfield.getText().trim();
            String connumText = connumfield.getText().trim();

            // 1. Empty check
            if (phoneText.isEmpty() || addressText.isEmpty() || dobText.isEmpty() ||
                connameText.isEmpty() || relationText.isEmpty() || connumText.isEmpty()) {

                JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!phoneText.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Phone number must contain only numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd")
                        .withResolverStyle(ResolverStyle.STRICT);
                LocalDate.parse(dobText, formatter);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "DOB must be valid and in format YYYY-MM-DD!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!connumText.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Contact number must contain only numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PersonalDetail pd = new PersonalDetail(loggedInUser.getUserId(), phoneText, addressText, dobText, connameText, relationText, connumText);
            
            String result = service.updatePersonalDetail(pd);
            
            if (result.contains("Successfully")) {
                JOptionPane.showMessageDialog(this, result, "Success", JOptionPane.INFORMATION_MESSAGE);
                PersonalDetail updatedPersonal = service.getPersonalDetailByUserId(loggedInUser.getUserId());
                PersonalDetailsPage personalpage = new PersonalDetailsPage(service, loggedInUser, updatedPersonal);
                personalpage.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, result, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred", "Error", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_login2ActionPerformed

    private void relationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationfieldActionPerformed

    private void connumfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connumfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connumfieldActionPerformed

    private void login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login4ActionPerformed
        // TODO add your handling code here:
        String role = loggedInUser.getRole();

        if ("HR".equalsIgnoreCase(role)) {

            HR_Main hrmainpage = new HR_Main(service, loggedInUser);
            hrmainpage.setVisible(true);

        } else if ("Employee".equalsIgnoreCase(role)) {

            Employee_Main empMain = new Employee_Main(service, loggedInUser);
            empMain.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Unknown role: " + role,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_login4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextArea addressfield;
    private javax.swing.JTextField connamefield;
    private javax.swing.JTextField connumfield;
    private javax.swing.JTextField dobfield;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel identification;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lname;
    private javax.swing.JButton login2;
    private javax.swing.JButton login3;
    private javax.swing.JButton login4;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField relationfield;
    // End of variables declaration//GEN-END:variables
}
