/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;
import model.EmployeeUser;
import model.HRUser;
import model.Request;
import model.User;
import shared.HRMInterface;

/**
 *
 * @author jason
 */
public class UpdateProfile extends javax.swing.JFrame {
    private HRMInterface service;
    private User loggedInUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateProfile.class.getName());

    /**
     * Creates new form UpdateProfile
     */
    public UpdateProfile(HRMInterface service, User user) {
        this.service = service;
        this.loggedInUser = user;
        initComponents();
    
        setTitle("Profile");
        setLocationRelativeTo(null);
        
        fnamefield.setText(loggedInUser.getFirstName());
        lnamefield.setText(loggedInUser.getLastName());
        identificationfield.setText(loggedInUser.getIc());
        emailfield.setText(loggedInUser.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        fnamefield = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        lnamefield = new javax.swing.JTextField();
        identification = new javax.swing.JLabel();
        identificationfield = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        login3 = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        login4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Title.setText("Profile");

        fname.setText("First Name");

        fnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamefieldActionPerformed(evt);
            }
        });

        lname.setText("Last Name");

        lnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnamefieldActionPerformed(evt);
            }
        });

        identification.setText("IC/Passport");

        identificationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificationfieldActionPerformed(evt);
            }
        });

        email.setText("Email");

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });

        login3.setText("Back");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login3ActionPerformed(evt);
            }
        });

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        login4.setText("Main");
        login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login3)
                                .addGap(30, 30, 30)
                                .addComponent(updatebutton)
                                .addGap(33, 33, 33)
                                .addComponent(login4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lname)
                                    .addComponent(identification)
                                    .addComponent(email))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identificationfield)
                                    .addComponent(lnamefield)
                                    .addComponent(fnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(emailfield)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Title)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname)
                    .addComponent(fnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identification, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login3)
                    .addComponent(updatebutton)
                    .addComponent(login4))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamefieldActionPerformed

    private void lnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnamefieldActionPerformed

    private void identificationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificationfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificationfieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login3ActionPerformed
        // TODO add your handling code here:
        Profile profilepage = new Profile(service, loggedInUser);
        profilepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login3ActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        try {
            String fnameText = fnamefield.getText().trim();
            String lnameText = lnamefield.getText().trim();
            String icText = identificationfield.getText().trim();
            String emailText = emailfield.getText().trim();

            if (fnameText.isEmpty() || lnameText.isEmpty() || icText.isEmpty() ||
                emailText.isEmpty()) {

                JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!icText.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "IC/Passport must contain only numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!emailText.contains("@") || !emailText.contains(".")) {
                JOptionPane.showMessageDialog(this, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String role = loggedInUser.getRole();
            User user;

            if (role.equalsIgnoreCase("HR")) {
                user = new HRUser(loggedInUser.getUserId(), fnameText, lnameText, icText, emailText);
            } else if (role.equalsIgnoreCase("Employee")) {
                user = new EmployeeUser(loggedInUser.getUserId(), fnameText, lnameText, icText, emailText);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid role!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            
            try (
                Socket socket = new Socket("localhost", 5000);
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
            ) {

                out.flush();
                
                Request req = new Request("UPDATE_PROFILE", user);
                out.writeObject(req);
                out.flush();
                
                String result = (String) in.readObject();
                
                if (result.contains("Successfully")) {
                    JOptionPane.showMessageDialog(this, result, "Success", JOptionPane.INFORMATION_MESSAGE);
                    User updatedUser = service.getUser(loggedInUser.getUserId());
                    Profile profilepage = new Profile(service, updatedUser);
                    profilepage.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, result, "Error", JOptionPane.ERROR_MESSAGE);
                }    
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred", "Error", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login4ActionPerformed
        // TODO add your handling code here:
        String role = loggedInUser.getRole();

        if ("HR".equalsIgnoreCase(role)) {

            HR_Main hrmainpage = new HR_Main(service, loggedInUser);
            hrmainpage.setVisible(true);

        } else if ("Employee".equalsIgnoreCase(role)) {

            Employee_Main empMain = new Employee_Main(service, loggedInUser);
            empMain.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Unknown role: " + role,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_login4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fnamefield;
    private javax.swing.JLabel identification;
    private javax.swing.JTextField identificationfield;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField lnamefield;
    private javax.swing.JButton login3;
    private javax.swing.JButton login4;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
